language: php

php:
  - 7.2
  - 7.3
  - 7.4

script: ant -logger org.apache.tools.ant.NoBannerLogger -Dphpmd.enabled=false -Dpdepend.enabled=false -Dphpcpd.enabled=false -Dphploc.enabled=false -Dcodesniffer.enabled=false
